-- Migration: 009_create_verification_engine_tables
-- Description: Creates the tables needed for the milestone negotiation chat, AI spec benchmarks, and spec approvals.

-- 1. Milestone Messages (Negotiation Chat)
CREATE TABLE IF NOT EXISTS milestone_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    milestone_id UUID NOT NULL REFERENCES milestones(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES users(id) ON DELETE SET NULL, -- Null if sent by AI/System
    sender_role VARCHAR(20) NOT NULL CHECK (sender_role IN ('client', 'developer', 'ai')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_milestone_messages_milestone_id ON milestone_messages(milestone_id);

-- Enable RLS for real-time security
ALTER TABLE milestone_messages ENABLE ROW LEVEL SECURITY;

-- Note: The exact RLS policy to allow developers/clients to read their own chats 
-- will depend on how Supabase is wired up to the API, but typically looks like:
-- CREATE POLICY "Users can view their own milestone chats"
-- ON milestone_messages FOR SELECT
-- USING (...);


-- 2. Milestone Specs (The locked benchmark generated by AI)
CREATE TABLE IF NOT EXISTS milestone_specs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    milestone_id UUID NOT NULL REFERENCES milestones(id) ON DELETE CASCADE,
    version INT NOT NULL DEFAULT 1,
    chat_thread_id UUID REFERENCES milestone_messages(id),
    spec_data JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'locked', 'archived')),
    locked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Ensure a milestone only has one 'locked' or 'draft' spec at a time
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_active_spec ON milestone_specs(milestone_id) WHERE status IN ('draft', 'locked');


-- 3. Spec Approvals (Tracks which party approved the draft)
CREATE TABLE IF NOT EXISTS spec_approvals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    spec_id UUID NOT NULL REFERENCES milestone_specs(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('client', 'developer')),
    approved_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE(spec_id, user_id)
);
